#! /bin/sh

${HOME}/bin/scripts/bspwm-startup.sh
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d 1 2 3 4 5 6

bspc config border_width	2
bspc config window_gap		4

bspc config split_ratio          0.602
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color "$color1"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color6"
bspc config presel_feedback_color "$color6"

bspc rule -a Galculator state=floating
